### ISSUE TITLE
Can you define how to use this 

### ISSUE THREAD

**Issue by MOONANGEL12** [DmitrijVC/Discord-CopyPaste2#1]
What is the command that we have to use to run it

**Comment by FssAy** [comment]
This project is deprecated. There were some Discord updates that this version doesn't support.

But if you want to use it anyway... 
Download the project, open `main.py`, change `"TOKEN"` to your account token. Run `main.py` and then send a command to this account on which the selfbot is running:
`<prefix><command> <GuildID-Original> <GuildID-Target>` 
so for example:
`cp2 copy 306492991286804480 806412331286123499`
