### ISSUE TITLE
how to fix this:

### ISSUE THREAD

**Issue by kolekcjo1ner** [DmitrijVC/Discord-CopyPaste2#2]
Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\Users\Kacper\Desktop\Szerver kopier> & C:/Users/Kacper/AppData/Local/Programs/Python/Python38-32/python.exe "c:/Users/Kacper/Desktop/Szerver kopier/main.py"
Traceback (most recent call last):
  File "c:/Users/Kacper/Desktop/Szerver kopier/main.py", line 1, in <module>
    import discord.py
ModuleNotFoundError: No module named 'discord'
PS C:\Users\Kacper\Desktop\Szerver kopier>

**Comment by kolekcjo1ner** [comment]
Ok i fixed this

**Comment by FssAy** [comment]
This project is deprecated.
